version: '3'
networks:
  infra_chatbot:
    external: true
services:
  plugin_weather_1:
    image: plugin_weather
    build: ./
    container_name: plugin_weather_1
    restart: always
    networks:
      - infra_chatbot
    env_file:
      - .env
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 128M
    logging:
      driver: json-file
      options:
        max-file: '5'
        max-size: 10m
